name: Pull Request

on: [push, pull_request]
  #pull_request:
    #types: [opened, synchronize]
    #branches: [main]
    #push:
      #paths:
        #- .github/workflows/pull-request.yml             

env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Build Project
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Build Project
        run: pnpm test

  typescript:
    runs-on: ubuntu-latest
    steps:
                  - name: Checkout Git
                    uses: actions/checkout@v4
            
                  - name: Configure Worflow
                    uses: ./.github/actions/configure
            
                  - name: Check TypeScript
                    run: pnpm tsc
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v4

      - name: Configure Worflow
        uses: ./.github/actions/configure

      - name: Check ESLint
        run: pnpm lint

  knip:
    runs-on: ubuntu-latest
    steps:
            - name: Checkout Git
              uses: actions/checkout@v4
      
            - name: Configure Worflow
              uses: ./.github/actions/configure
      
            - name: Check unused files, dependencies, exports
              run: pnpm knip      



