name: release-please

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full commit history is fetched for release-please

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensures the correct Node.js version is used
          cache: 'pnpm' # Caches dependencies for faster builds

      - name: Install Dependencies
        run: pnpm install # Installs dependencies required for release-please

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: next-product-site # Matches the name in package.json
          default-branch: main
          changelog-types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
          token: ${{ secrets.GITHUB_TOKEN }} # Uses GitHub token for authentication